export function generateReportText(scanHistory, awarenessScore, stats, simulatorScore, sessionStart) {
  const now = new Date();
  const sessionDuration = Math.floor((now - sessionStart) / 60000);
  const reportId = 'RPT-' + Date.now().toString(36).toUpperCase();

  const getLevel = (s) => {
    if (s >= 81) return 'Cyber Defender';
    if (s >= 61) return 'Security Pro';
    if (s >= 41) return 'Cyber Aware';
    if (s >= 21) return 'Trainee';
    return 'Novice Analyst';
  };

  let report = `
════════════════════════════════════════════
  SENTINEL AI — THREAT INTELLIGENCE REPORT
════════════════════════════════════════════

Report ID: ${reportId}
Generated: ${now.toLocaleString()}
Session Duration: ${sessionDuration} minutes

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ANALYST OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Awareness Score: ${awarenessScore} / 100
Rating: ${getLevel(awarenessScore)}
${simulatorScore !== null ? `Simulator Score: ${simulatorScore} points` : 'Simulator: Not completed'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  THREAT STATISTICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Scans: ${stats.totalScans}
Threats Detected: ${stats.threatsDetected}
Safe Content Cleared: ${stats.safeCleared}

By Category:
  • Phishing: ${stats.phishingCount}
  • Malware: ${stats.malwareCount}
  • Social Engineering: ${stats.socialEngCount}

By Severity:
  • High: ${stats.highSeverity}
  • Medium: ${stats.mediumSeverity}
  • Low: ${stats.lowSeverity}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  DETAILED FINDINGS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  scanHistory.forEach((scan, i) => {
    report += `
── Scan #${i + 1} ──────────────────────────
Threat ID: ${scan.analysis.threat_id}
Classification: ${scan.analysis.classification}
Severity: ${scan.analysis.severity}
Confidence: ${scan.analysis.confidence}%
Time: ${new Date(scan.timestamp).toLocaleTimeString()}

Summary: ${scan.analysis.headline}
${scan.analysis.explanation}

Indicators: ${scan.analysis.indicators?.join(', ') || 'None'}
Action: ${scan.analysis.recommended_action}
`;
  });

  report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by SENTINEL AI
  CODESTORM HACKATHON 2K26
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  return { report, reportId };
}

export function generateReportJSON(scanHistory, awarenessScore, stats, simulatorScore, sessionStart) {
  return {
    meta: {
      report_id: 'RPT-' + Date.now().toString(36).toUpperCase(),
      generated_at: new Date().toISOString(),
      platform: 'SENTINEL AI',
      version: '1.0.0',
    },
    analyst: {
      awareness_score: awarenessScore,
      simulator_score: simulatorScore,
      session_start: new Date(sessionStart).toISOString(),
    },
    statistics: stats,
    scans: scanHistory.map(s => ({
      id: s.id,
      timestamp: s.timestamp,
      content_preview: s.content?.substring(0, 100),
      content_type: s.contentType,
      analysis: s.analysis,
    })),
  };
}
