import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Shield, ShieldAlert, Copy, Flag, Share2, Bookmark, RotateCcw, ToggleLeft, ToggleRight } from 'lucide-react';
import toast from 'react-hot-toast';
import { useThreatAnalysis } from '../hooks/useThreatAnalysis';
import AnalysisLoader from '../components/AnalysisLoader';
import ThreatMeter from '../components/ThreatMeter';
import ThreatDNA from '../components/ThreatDNA';

const TABS = ['EMAIL', 'URL', 'MESSAGE', 'RAW CODE'];
const PLACEHOLDERS = {
  EMAIL: 'Paste a suspicious email here...',
  URL: 'Enter a URL to scan...',
  MESSAGE: 'Drop a suspicious message...',
  'RAW CODE': 'Paste suspicious code snippet...',
};

const CLASSIFICATION_COLORS = {
  Phishing: '#FF2D55',
  Malware: '#A855F7',
  'Social Engineering': '#FFB300',
  Safe: '#00E676',
};

const SEVERITY_SCORES = { Low: 25, Medium: 55, High: 85 };

export default function Analyzer() {
  const [tab, setTab] = useState('EMAIL');
  const [content, setContent] = useState('');
  const [deepScan, setDeepScan] = useState(false);
  const [placeholderIdx, setPlaceholderIdx] = useState(0);
  const { loading, result, error, loadingStage, loadingStages, analyze, reset } = useThreatAnalysis();

  const placeholderTexts = [
    PLACEHOLDERS[tab],
    'Try: "Your account has been suspended..."',
    'Try: "Click here to verify your identity..."',
    'Paste any suspicious content to analyze...',
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setPlaceholderIdx(prev => (prev + 1) % placeholderTexts.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [tab]);

  const handleAnalyze = () => {
    if (!content.trim()) {
      toast.error('Please enter content to analyze');
      return;
    }
    analyze(content, tab, deepScan);
  };

  const handleCopyReport = () => {
    if (!result) return;
    const report = `SENTINEL AI Threat Report
━━━━━━━━━━━━━━━━━━━━━━━━━
Threat ID: ${result.threat_id}
Classification: ${result.classification}
Severity: ${result.severity}
Confidence: ${result.confidence}%
━━━━━━━━━━━━━━━━━━━━━━━━━
${result.headline}

${result.explanation}

Why Dangerous: ${result.why_dangerous}
Attack Vector: ${result.attack_vector}
Recommended Action: ${result.recommended_action}

Indicators: ${result.indicators?.join(', ')}
━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SENTINEL AI`;

    navigator.clipboard.writeText(report);
    toast.success('Report copied to clipboard!');
  };

  const classColor = result ? CLASSIFICATION_COLORS[result.classification] || '#00D9FF' : '#00D9FF';

  return (
    <div className="space-y-5">
      {/* Loading Overlay */}
      <AnimatePresence>
        {loading && (
          <AnalysisLoader
            stage={loadingStage}
            stages={loadingStages}
          />
        )}
      </AnimatePresence>

      {/* Page Title */}
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-xl font-black text-white flex items-center gap-2 font-mono tracking-wide">
          <ShieldAlert className="w-6 h-6 text-sentinel-cyan" />
          Threat Analyzer
        </h1>
        <p className="text-xs text-sentinel-text-muted mt-0.5 font-mono">
          Submit any suspicious content for AI-powered threat analysis
        </p>
      </motion.div>

      {/* Input Section */}
      {!result && (
        <motion.div
          className="rounded-xl p-5 space-y-4"
          style={{ background: 'rgba(11, 17, 32, 0.6)', border: '1px solid rgba(0, 217, 255, 0.06)' }}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
        >
          {/* Tab Switcher */}
          <div className="flex gap-1">
            {TABS.map(t => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className="flex-1 py-2 px-3 rounded-lg text-[11px] font-bold font-mono transition-all"
                style={{
                  background: tab === t ? 'rgba(0, 217, 255, 0.12)' : 'transparent',
                  color: tab === t ? '#00D9FF' : '#64748B',
                  border: tab === t ? '1px solid rgba(0, 217, 255, 0.2)' : '1px solid transparent',
                }}
              >
                {t}
              </button>
            ))}
          </div>

          {/* Textarea */}
          <textarea
            value={content}
            onChange={e => setContent(e.target.value)}
            placeholder={placeholderTexts[placeholderIdx]}
            rows={7}
            className="w-full rounded-lg p-4 text-[13px] font-mono leading-relaxed resize-none focus:outline-none focus:ring-1 focus:ring-sentinel-cyan/30"
            style={{
              background: 'rgba(17, 24, 39, 0.6)',
              border: '1px solid rgba(30, 41, 59, 0.3)',
              color: '#E2E8F0',
            }}
          />

          {/* Controls Row */}
          <div className="flex items-center justify-between">
            <button
              onClick={() => setDeepScan(!deepScan)}
              className="flex items-center gap-2 text-[12px] font-mono transition-colors"
              style={{ color: deepScan ? '#00D9FF' : '#64748B' }}
            >
              {deepScan ? <ToggleRight className="w-5 h-5" /> : <ToggleLeft className="w-5 h-5" />}
              Deep Scan
            </button>

            <button
              onClick={handleAnalyze}
              disabled={loading || !content.trim()}
              className="px-6 py-2.5 rounded-lg text-sm font-bold font-mono disabled:opacity-30 transition-all hover:scale-105"
              style={{ background: 'linear-gradient(135deg, #00D9FF, #0088FF)', color: '#0A0E1A' }}
            >
              <Search className="w-4 h-4 inline mr-2" />
              ANALYZE THREAT
            </button>
          </div>
        </motion.div>
      )}

      {/* Error */}
      {error && (
        <motion.div
          className="p-4 rounded-xl"
          style={{ background: 'rgba(255, 45, 85, 0.05)', border: '1px solid rgba(255, 45, 85, 0.15)' }}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
        >
          <p className="text-sentinel-red text-xs font-mono">⚠️ {error}</p>
          <button onClick={reset}
            className="flex items-center gap-1.5 mt-2 text-[11px] font-mono text-sentinel-text-muted hover:text-sentinel-cyan transition-colors">
            <RotateCcw className="w-3 h-3" /> Try Again
          </button>
        </motion.div>
      )}

      {/* Results */}
      <AnimatePresence>
        {result && (
          <motion.div
            className="space-y-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
          >
            {/* THREAT VERDICT */}
            <motion.div
              className="rounded-xl p-6"
              style={{
                background: 'rgba(11, 17, 32, 0.6)',
                border: `1px solid ${classColor}20`,
              }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
            >
              <div className="flex flex-col lg:flex-row items-center gap-6">
                {/* Classification */}
                <div className="flex flex-col items-center gap-2">
                  <motion.div
                    className="px-5 py-2 rounded-lg text-base font-black font-mono tracking-wider"
                    style={{
                      background: `${classColor}12`,
                      color: classColor,
                      border: `1px solid ${classColor}30`,
                    }}
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: 'spring', delay: 0.3 }}
                  >
                    {result.classification === 'Safe' ? '✅' : '🚨'} {result.classification?.toUpperCase()}
                  </motion.div>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] text-sentinel-text-muted font-mono">Confidence:</span>
                    <span className="text-sm font-bold font-mono" style={{ color: classColor }}>{result.confidence}%</span>
                  </div>
                  <p className="text-[10px] font-mono text-sentinel-text-muted">{result.threat_id}</p>
                </div>

                {/* Severity Meter */}
                <div className="flex-1 flex justify-center">
                  <ThreatMeter score={SEVERITY_SCORES[result.severity] || 25} severity={result.severity} size={160} />
                </div>
              </div>

              <motion.p
                className="text-center text-sm font-semibold mt-4 font-mono"
                style={{ color: classColor }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5 }}
              >
                {result.headline}
              </motion.p>
            </motion.div>

            {/* AI INTELLIGENCE REPORT */}
            <motion.div
              className="rounded-xl p-5"
              style={{ background: 'rgba(11, 17, 32, 0.6)', border: '1px solid rgba(0, 217, 255, 0.06)' }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
            >
              <h3 className="text-xs font-bold text-white mb-4 font-mono flex items-center gap-2">
                <Shield className="w-4 h-4 text-sentinel-cyan" />
                INTELLIGENCE REPORT
              </h3>

              <div className="space-y-3">
                <ReportSection icon="🔍" title="What was detected" content={result.explanation} delay={0.3} />
                <ReportSection icon="⚠️" title="Why it's dangerous" content={result.why_dangerous} delay={0.5} />
                <ReportSection icon="🎯" title="Attack vector" content={result.attack_vector} delay={0.7} />
                <ReportSection icon="🛡️" title="Recommended action" content={result.recommended_action} delay={0.9} />
              </div>

              {/* Indicator Chips */}
              {result.indicators && result.indicators.length > 0 && (
                <motion.div
                  className="mt-4 pt-3"
                  style={{ borderTop: '1px solid rgba(30, 41, 59, 0.3)' }}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 1 }}
                >
                  <div className="flex flex-wrap gap-1.5">
                    {result.indicators.map((ind, i) => (
                      <motion.span
                        key={i}
                        className="indicator-chip text-[10px]"
                        initial={{ opacity: 0, scale: 0.8 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 1.1 + i * 0.08 }}
                      >
                        {ind}
                      </motion.span>
                    ))}
                  </div>
                </motion.div>
              )}

              {/* Educational Tip */}
              {result.educational_tip && (
                <motion.div
                  className="mt-3 p-2.5 rounded-lg"
                  style={{ background: 'rgba(0, 217, 255, 0.04)', border: '1px solid rgba(0, 217, 255, 0.08)' }}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 1.2 }}
                >
                  <p className="text-[11px] text-sentinel-cyan font-mono">
                    💡 {result.educational_tip}
                  </p>
                </motion.div>
              )}
            </motion.div>

            {/* THREAT DNA */}
            <motion.div
              className="rounded-xl p-5"
              style={{ background: 'rgba(11, 17, 32, 0.6)', border: '1px solid rgba(0, 217, 255, 0.06)' }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
            >
              <h3 className="text-xs font-bold text-white mb-3 font-mono">🧬 THREAT DNA</h3>
              <ThreatDNA dna={result.dna} />
            </motion.div>

            {/* QUICK ACTIONS */}
            <motion.div
              className="rounded-xl p-5"
              style={{ background: 'rgba(11, 17, 32, 0.6)', border: '1px solid rgba(0, 217, 255, 0.06)' }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
            >
              <div className="flex flex-wrap gap-2">
                <ActionBtn icon={<Shield className="w-3.5 h-3.5" />} label="Mark Safe" onClick={() => toast.success('Marked as safe')} />
                <ActionBtn icon={<Flag className="w-3.5 h-3.5" />} label="Report False Positive" onClick={() => toast.success('Reported')} variant="danger" />
                <ActionBtn icon={<Share2 className="w-3.5 h-3.5" />} label="Share Analysis" onClick={() => {navigator.clipboard.writeText(window.location.href); toast.success('Link copied');}} />
                <ActionBtn icon={<Bookmark className="w-3.5 h-3.5" />} label="Add to Watchlist" onClick={() => toast.success('Added to watchlist')} />
                <ActionBtn icon={<Copy className="w-3.5 h-3.5" />} label="Copy Report" onClick={handleCopyReport} variant="primary" />
              </div>
            </motion.div>

            {/* New Analysis */}
            <motion.div className="flex justify-center" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}>
              <button
                onClick={() => { reset(); setContent(''); }}
                className="px-6 py-2.5 rounded-lg text-sm font-bold font-mono transition-all hover:scale-105"
                style={{ background: 'linear-gradient(135deg, #00D9FF, #0088FF)', color: '#0A0E1A' }}
              >
                <RotateCcw className="w-4 h-4 inline mr-2" />
                New Analysis
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function ActionBtn({ icon, label, onClick, variant = 'secondary' }) {
  const styles = {
    primary: { background: 'linear-gradient(135deg, #00D9FF, #0088FF)', color: '#0A0E1A', border: 'none' },
    danger: { background: 'rgba(255, 45, 85, 0.08)', color: '#FF2D55', border: '1px solid rgba(255, 45, 85, 0.15)' },
    secondary: { background: 'rgba(0, 217, 255, 0.06)', color: '#00D9FF', border: '1px solid rgba(0, 217, 255, 0.12)' },
  };
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-[11px] font-mono font-semibold transition-all hover:scale-105"
      style={styles[variant]}
    >
      {icon} {label}
    </button>
  );
}

function ReportSection({ icon, title, content, delay = 0 }) {
  const [displayText, setDisplayText] = useState('');

  useEffect(() => {
    if (!content) return;
    let i = 0;
    const timer = setTimeout(() => {
      const interval = setInterval(() => {
        if (i <= content.length) {
          setDisplayText(content.slice(0, i));
          i++;
        } else {
          clearInterval(interval);
        }
      }, 12);
      return () => clearInterval(interval);
    }, delay * 1000);
    return () => clearTimeout(timer);
  }, [content, delay]);

  return (
    <motion.div
      className="flex gap-2.5"
      initial={{ opacity: 0, x: -8 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay }}
    >
      <span className="text-base flex-shrink-0 mt-0.5">{icon}</span>
      <div>
        <h4 className="text-[11px] font-semibold text-white font-mono mb-0.5">{title}</h4>
        <p className="text-[12px] text-sentinel-text-dim leading-relaxed">
          {displayText || content}
        </p>
      </div>
    </motion.div>
  );
}
